UltraBudget2/UltraBudget2/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using UltraBudget2.Models;
using UltraBudget2.Repositories;

namespace UltraBudget2.Controllers
{
    public class AccountsController : Controller
    {
        private IBudgetRepository _repository { get; set; }

        public AccountsController(IBudgetRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var accounts = _repository.GetAccounts();
            if (accounts.Any())
            {
                foreach (var account in accounts)
                {
                    account.Balance = _repository.GetTransactions().Where(t => t.Account == account.Name).Sum(t => t.Amount);
                }
            }

            return View(accounts);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(Account account)
        {
            var existingAccount = _repository.GetAccount(account.Id);
            return View(existingAccount);
        }

        public IActionResult Edit(string id)
        {
            var existingAccount = _repository.GetAccount(Guid.Parse(id));
            return View(existingAccount);
        }

        [HttpPost]
        public IActionResult Create([FromForm] Account account)
        {
            account.Id = Guid.NewGuid();
            // TODO: check if Account with same name already exists
            _repository.UpsertAccount(account);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            _repository.DeleteAccount(Guid.Parse(id));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit([FromForm] Account account)
        {
            _repository.UpsertAccount(account);
            // TODO: update all transactions in this account
            return RedirectToAction("Index");
        }
    }
}

UltraBudget2/UltraBudget2/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using UltraBudget2.Extensions;
using UltraBudget2.Models;
using UltraBudget2.Repositories;

namespace UltraBudget2.Controllers
{
    public class TransactionsController : Controller
    {
        private IBudgetRepository _repository { get; set; }

        public TransactionsController(IBudgetRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            TempData["Categories"] = _repository.GetSubCategoriesDropdown();
            TempData["Accounts"] = _repository.GetAccountsDropdown();
            return View(_repository.GetTransactions());
        }

        public IActionResult Create()
        {
            TempData["Categories"] = _repository.GetSubCategoriesDropdown();
            TempData["Accounts"] = _repository.GetAccountsDropdown();
            return View();
        }

        public IActionResult Delete(Transaction transaction)
        {
            var existingTransaction = _repository.GetTransaction(transaction.Id);
            return View(existingTransaction);
        }

        public IActionResult Edit(string id)
        {
            TempData["Categories"] = _repository.GetSubCategoriesDropdown();
            TempData["Accounts"] = _repository.GetAccountsDropdown();
            var existingTransaction = _repository.GetTransaction(Guid.Parse(id));
            return View(existingTransaction);
        }

        [HttpPost]
        public IActionResult Create([FromForm] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.Id = Guid.NewGuid();
                _repository.UpsertTransaction(transaction);
            }
            else
            {
                TempData["ErrorMessage"] = "Invalid input for transaction.";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            _repository.DeleteTransaction(Guid.Parse(id));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit([FromForm] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _repository.UpsertTransaction(transaction);
            }
            else
            {
                TempData["ErrorMessage"] = "Invalid input for transaction.";
            }
            return RedirectToAction("Index");
        }
    }
}

UltraBudget2/UltraBudget2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="height:100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UltraBudget2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        input {
            box-sizing: border-box;
            width:100%;
        } 
    </style>
</head>
<body style="height:100%">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UltraBudget2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Budget</a></li>
                    <li><a asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    <li><a asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-controller="Home" asp-action="Example">Generate Example Data</a></li>
                    <li><a asp-controller="Home" asp-action="Export">Export</a></li>
                </ul>
                @* Not working, no idea why... *@
                @*<form enctype="multipart/form-data" asp-controller="Home" asp-action="Index" method="post" class="nav navbar-nav navbar-right">
                    <input id="files" type="file" name="file" />
                    <input type="submit" value="Import" />
                </form>*@
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" style="height:100%">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; 2018 - UltraBudget2</p>
        </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>